-- ============================================================
-- 03_gold_tables.sql  –  Gold layer (analytics star schema)
-- ============================================================
-- Star schema: FactSales at centre, DimDate / DimCustomer / DimProduct
-- as SCD Type 2 conformed dimensions.
--
-- Key design decisions:
--   • Surrogate keys (BIGINT) – row_number() over natural key ORDER.
--     surrogate_key = -1 reserved for the UNKNOWN member sentinel row.
--   • Attribute hash (SHA-256) – drives SCD2 change detection without
--     comparing every tracked column individually.
--   • Transaction hash (SHA-256 over business key columns) – enables
--     idempotent fact upserts; duplicates in source are suppressed.
--   • Temporal FK join – fact stores the SK valid at transaction_date;
--     no re-join required at query time.
--   • Late-arriving bridge – facts with no matching dimension row get
--     customer_key / product_key = -1 and a PENDING entry in the
--     bridge. TF_Resolve_Late_Dimensions backfills the FK later.
-- ============================================================

-- ── DimDate (generated, no SCD, full overwrite) ──────────────────────────────

CREATE TABLE IF NOT EXISTS {catalog_name}.gold.dim_date
(
    date_key        INT         NOT NULL  COMMENT 'Surrogate key in yyyyMMdd format (e.g. 20260316)',
    calendar_date   DATE        NOT NULL  COMMENT 'Calendar date (PK for joins from fact)',
    year            INT                   COMMENT 'Calendar year',
    quarter         INT                   COMMENT 'Quarter number (1–4)',
    month           INT                   COMMENT 'Month number (1–12)',
    month_name      STRING                COMMENT 'Full month name (January … December)',
    week_of_year    INT                   COMMENT 'ISO week number',
    day_of_week     INT                   COMMENT 'Day-of-week (1=Sunday, 7=Saturday per Spark)',
    day_name        STRING                COMMENT 'Full day name (Monday … Sunday)',
    is_weekend      BOOLEAN               COMMENT 'True if Saturday or Sunday'
)
USING DELTA
COMMENT 'Calendar dimension. Generated by TF_Gold_Load_Engine (object_type=dimension, no scd_type). Full overwrite.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);


-- ── DimCustomer (SCD Type 2) ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS {catalog_name}.gold.dim_customer
(
    -- Surrogate key
    customer_key    BIGINT      NOT NULL  COMMENT 'Surrogate key. -1 = UNKNOWN sentinel member.',

    -- Natural / business key
    customer_id     STRING      NOT NULL  COMMENT 'SAP customer master key (natural key)',

    -- Tracked slowly-changing attributes
    customer_name   STRING                COMMENT 'Full legal entity name',
    region          STRING                COMMENT 'Sales region code',
    channel         STRING                COMMENT 'Trade channel',

    -- Change-detection fingerprint
    attribute_hash  STRING                COMMENT 'SHA-256 of tracked columns (||-delimited). Change → new SCD2 row.',

    -- SCD2 temporal columns
    effective_from  DATE        NOT NULL  COMMENT 'Date from which this version is valid (inclusive)',
    effective_to    DATE        NOT NULL  COMMENT 'Date until which this version is valid (inclusive). 9999-12-31 = current.',
    is_current      BOOLEAN     NOT NULL  COMMENT 'True if this is the most-recent active version',

    -- Pipeline audit
    batch_id        STRING                COMMENT 'SD batch_id that sourced this version'
)
USING DELTA
COMMENT 'SCD Type 2 customer dimension. Unknown sentinel: customer_key=-1, customer_id=UNKNOWN, effective 1900–9999.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);


-- ── DimProduct (SCD Type 2) ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS {catalog_name}.gold.dim_product
(
    product_key     BIGINT      NOT NULL  COMMENT 'Surrogate key. -1 = UNKNOWN sentinel member.',
    product_id      STRING      NOT NULL  COMMENT 'SAP material number (natural key)',
    product_name    STRING                COMMENT 'Material description',
    brand           STRING                COMMENT 'Brand name',
    category        STRING                COMMENT 'Product category',
    status          STRING                COMMENT 'Material status (ACTIVE / DELISTED)',

    attribute_hash  STRING                COMMENT 'SHA-256 of tracked columns. Change → new SCD2 row.',

    effective_from  DATE        NOT NULL,
    effective_to    DATE        NOT NULL,
    is_current      BOOLEAN     NOT NULL,

    batch_id        STRING
)
USING DELTA
COMMENT 'SCD Type 2 product dimension. Unknown sentinel: product_key=-1, product_id=UNKNOWN, effective 1900–9999.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);


-- ── FactSales ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS {catalog_name}.gold.fact_sales
(
    -- Idempotency key (dedup / upsert merge condition)
    transaction_hash    STRING      NOT NULL  COMMENT 'SHA-256 over transaction_hash_columns. Enables idempotent upserts.',

    -- Degenerate dimension (transaction descriptor)
    sales_id            STRING                COMMENT 'SAP sales document line ID',

    -- Foreign keys to dimensions
    date_key            INT                   COMMENT 'FK → gold.dim_date.date_key (yyyyMMdd)',
    customer_key        BIGINT                COMMENT 'FK → gold.dim_customer.customer_key. -1 if late-arriving.',
    product_key         BIGINT                COMMENT 'FK → gold.dim_product.product_key. -1 if late-arriving.',

    -- Measures
    quantity            INT                   COMMENT 'Order quantity',
    net_amount          DECIMAL(18, 2)        COMMENT 'Net sales value (JPY)',

    -- Degenerate attributes
    currency            STRING                COMMENT 'Transaction currency code',
    source_system       STRING                COMMENT 'Source system identifier',
    batch_id            STRING                COMMENT 'Silver batch_id (original SD run)',

    -- Late-arriving dimension flag
    needs_resolution    BOOLEAN               COMMENT 'True when at least one surrogate key = -1. Cleared by TF_Resolve_Late_Dimensions.',

    -- Gold load audit
    fact_batch_id       STRING                COMMENT 'TF batch_id when this row was loaded to Gold',
    fact_loaded_at      TIMESTAMP             COMMENT 'UTC timestamp of Gold load'
)
USING DELTA
PARTITIONED BY (fact_batch_id)
COMMENT 'Central fact table. Upserted on transaction_hash. Temporal FK resolution via late_arriving_dimension_bridge.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true',
    'delta.dataSkippingNumIndexedCols' = '4'
);


-- ── Late-Arriving Dimension Bridge ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS {catalog_name}.gold.late_arriving_dimension_bridge
(
    -- Idempotency key for bridge upserts
    resolution_hash         STRING      NOT NULL  COMMENT 'SHA-256(transaction_hash | dimension_name | natural_key). Prevents duplicate bridge entries.',

    -- Linkage back to the fact row
    transaction_hash        STRING      NOT NULL  COMMENT 'FK → gold.fact_sales.transaction_hash',
    transaction_id          STRING                COMMENT 'Business transaction identifier (sales_id)',
    dimension_name          STRING      NOT NULL  COMMENT 'Which dimension is unresolved (customer / product)',
    natural_key             STRING      NOT NULL  COMMENT 'The natural key value that had no matching dimension row at fact load time',
    transaction_date        DATE                  COMMENT 'Transaction date used for temporal FK resolution',
    fact_key_column         STRING                COMMENT 'Surrogate key column name in the fact table (customer_key / product_key)',
    fact_table_name         STRING                COMMENT 'Fully-qualified fact table name',

    -- Load context
    batch_id                STRING                COMMENT 'Fact batch_id when this PENDING entry was created',

    -- Resolution state
    resolution_status       STRING      NOT NULL  COMMENT 'PENDING → fact row has SK = -1. RESOLVED → FK has been backfilled.',
    resolved_surrogate_key  BIGINT                COMMENT 'Filled after successful resolution. NULL while PENDING.',
    first_seen_timestamp    TIMESTAMP             COMMENT 'UTC timestamp when this bridge entry was first created',
    resolved_timestamp      TIMESTAMP             COMMENT 'UTC timestamp when resolution succeeded. NULL while PENDING.'
)
USING DELTA
COMMENT 'Tracks facts with unresolved dimension FKs. TF_Resolve_Late_Dimensions uses this table to backfill SKs.'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact'   = 'true'
);
